### ISSUE TITLE
Error on line 77 when using Ksampler GPU

### ISSUE THREAD

**Issue by MockbaTheBorg** [dawangraoming/ComfyUI_ksampler_gpu#2]
Hi there ... I am getting the following error when trying to use this ksampler.

![image](https://github.com/dawangraoming/ComfyUI_ksampler_gpu/assets/16762507/97e3d236-9a4f-499e-9c31-635d6026a67a)

Here is the workflow I am trying, very simple one.

![image](https://github.com/dawangraoming/ComfyUI_ksampler_gpu/assets/16762507/546477a1-083a-46db-99a1-b9138c6da90e)

I have applied the patch on the pull-request, line 26.
Line 26 reads:
```
generator = torch.Generator(device=device).manual_seed(seed)
```

Please verify. Thanks!

**Comment by TimurShaidulin** [comment]
Just comment it out. It's useless

**Comment by MockbaTheBorg** [comment]
Not sure what is useless.
What should I comment out?

**Comment by TimurShaidulin** [comment]
That was the short version. 
Here's the long version. It calls deprecated method (which was even deleted). So you have 3 options:
1. Rollback to comfyui commit which still has it
2. Comment line 77 and forget about controlnet for this sampler
3. Write your own implementation to support controlnet because I doubt author will do it

**Comment by MockbaTheBorg** [comment]
Ah ok. Got it now.

Actually in the meantime I wrote an empty latent and ksampler which allows
to select between CPU and GPU, so no need for this one anymore.

We can close this issue.
